import cloudinary.utils
import cloudinary
import cloudinary.uploader
from fastapi import UploadFile, HTTPException, status
from fastapi.concurrency import run_in_threadpool

from app.core.config import settings

cloudinary.config(
    cloud_name=settings.cloudinary_cloud_name,
    api_key=settings.cloudinary_api_key,
    api_secret=settings.cloudinary_api_secret,
    secure=True,
)


MAX_FILE_SIZE = 50 * 1024 * 1024  # 50 MB
ALLOWED_CONTENT_TYPES = {"image/jpeg", "image/png", "image/webp", "image/heic"}

async def upload_photo_to_cloudinary(file: UploadFile, event_id: str) -> dict:
    """
    Upload a single photo file to Cloudinary under a per-event folder.

    The Cloudinary SDK is synchronous, so the blocking call is offloaded to a
    worker thread via run_in_threadpool to keep the event loop responsive.

    Returns the info needed to save as Photo metadata in MongoDB.
    """
    file_content = await file.read()
    if len(file_content) > MAX_FILE_SIZE:
        raise HTTPException(
        status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
        detail=f"{file.filename} exceeds the 50 MB limit",
    )

    try:
        upload_result = await run_in_threadpool(
            cloudinary.uploader.upload,
            file_content,
            folder=f"photo_sharing/{event_id}",
            resource_type="image",
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to upload photo: {str(e)}",
        )

    return {
        "storage_key": upload_result["public_id"],
        "url": upload_result["secure_url"],
        "file_size": upload_result["bytes"],
    }

def build_thumbnail_url(storage_key: str, width: int = 400) -> str:
    """Build an on-the-fly resized URL from a Cloudinary public_id."""
    return cloudinary.CloudinaryImage(storage_key).build_url(
        width=width,
        crop="fill",
        quality="auto",
        fetch_format="auto",
    )



def build_download_url(storage_key: str, filename: str) -> str:
    """URL that forces a file download instead of opening in the browser."""
    url, _ = cloudinary.utils.cloudinary_url(
        storage_key,
        flags=f"attachment:{filename.rsplit('.', 1)[0]}",
        secure=True,
    )
    return url


def build_archive_url(storage_keys: list[str], archive_name: str) -> str:
    """Signed URL for a zip of the given photos, generated by Cloudinary on demand."""
    return cloudinary.utils.download_zip_url(
        public_ids=storage_keys,
        resource_type="image",
        target_public_id=archive_name,
        flatten_folders=True,
    )


async def delete_photo_from_cloudinary(storage_key: str) -> None:
    """Delete an asset from Cloudinary. Best-effort: never blocks the DB delete."""
    try:
        await run_in_threadpool(cloudinary.uploader.destroy, storage_key)
    except Exception:
        pass